### ISSUE TITLE
Does not support ruby 3.0.2

### ISSUE THREAD

**Issue by rcassity** [sj26/mailcatcher#483]
The `mailcatcher' command exists in these Ruby versions:
  2.2.5
  2.3.8
  2.5.0
  2.7.1
  2.7.2
  2.7.3

Mailcatcher breaks on ruby 3.0.2

**Comment by sj26** [comment]
Hm, this looks like a ruby version manager output, not an error running mailcatcher itself in ruby 3. Did you forget to install it in the version of ruby you’re using there? Try `gem install mailcatcher` first?

**Comment by sj26** [comment]
Oh sorry, I haven’t updated the gemspec. Mailcatcher is tested against maintained ruby versions, and so should probably be restricted to ruby 2.6+

https://www.ruby-lang.org/en/downloads/branches

I’ll update the gemspec and for the next release.

**Comment by rcassity** [comment]
Thank you!

**Comment by rcassity** [comment]
This is the error I am receiving. I do NOT have mailcatcher in my gemfile.

Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
`event_callback': undefined method `close' for 16:Integer (NoMethodError)
Did you mean?  clone

**Comment by sj26** [comment]
That looks like an old version of MailCatcher. Latest versions should include a version number, like:

```
Starting MailCatcher v0.8.1
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
```

Can you try upgrading with: `gem install mailcatcher` 

And confirm it's the latest version by `gem list mailcatcher`

**Comment by rcassity** [comment]
Thank you for your help. When I run gem install mailcatcher this is what I get:

Building native extensions. This could take a while...
ERROR:  Error installing mailcatcher:
	ERROR: Failed to build gem native extension.

    current directory: /Users/####/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thin-1.5.1/ext/thin_parser
/Users/###/.rbenv/versions/3.0.2/bin/ruby -I /Users/###/.rbenv/versions/3.0.2/lib/ruby/3.0.0 -r ./siteconf20210805-97504-r34kp5.rb extconf.rb
checking for main() in -lc... yes
creating Makefile

current directory: /Users/###/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thin-1.5.1/ext/thin_parser
make DESTDIR\= clean

current directory: /Users/####/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thin-1.5.1/ext/thin_parser
make DESTDIR\=
compiling parser.c
parser.rl:112:17: warning: comparison of integers of different signs: 'long' and 'unsigned long' [-Wsign-compare]
  assert(pe - p == len - off && "pointers aren't same distance");
         ~~~~~~ ^  ~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
parser.rl:142:7: error: implicit declaration of function 'thin_http_parser_has_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (thin_http_parser_has_error(parser) ) {
      ^
parser.rl:142:7: note: did you mean 'http_parser_has_error'?
./parser.h:44:5: note: 'http_parser_has_error' declared here
int http_parser_has_error(http_parser *parser);
    ^
parser.rl:144:14: error: implicit declaration of function 'thin_http_parser_is_finished' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  } else if (thin_http_parser_is_finished(parser) ) {
             ^
1 warning and 2 errors generated.
make: *** [parser.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/#####/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thin-1.5.1 for inspection.
Results logged to /Users/####/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-darwin-20/3.0.0/thin-1.5.1/gem_make.out


$gem list mailcatcher           

*** LOCAL GEMS ***

**Comment by sj26** [comment]
https://github.com/sj26/mailcatcher#ruby

> If you encounter issues installing [thin](https://rubygems.org/gems/thin), try:
> 
> ```
> gem install thin -v 1.5.1 -- --with-cflags="-Wno-error=implicit-function-declaration"
> ```

**Comment by rcassity** [comment]
Thank you! I did find a work around. I start mailcatcher in a branch with an older ruby version and then I can locally send emails after I checkout my new branch

**Comment by sj26** [comment]
Great! It should work on ruby 3.0.2 as well if you need, following the above.

I'll close this if you're working, though.

**Comment by rcassity** [comment]
Feel free to close it for now. I do not have to run it that much. Thank you for promptly helping me.
